### ISSUE TITLE
[BUG] <Update GeoChart Plugin>

### ISSUE THREAD

**Issue by kaminderpal** [Canadian-Geospatial-Platform/geoview#1568]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Geochart plugin fetch the layers from store and display the chart.
This functionality works only for one layer at a time. 

We need to update the geochart plugin, where all the layers which have charts, fetch the data when component mounts, instead of layer click on map.

### Expected Behavior

We need to update the geochart plugin, where all the layers which have charts, fetch the data when component mounts, instead of layer click on map.

### Steps To Reproduce

1) Visit https://kaminderpal.github.io/geoview/package-footer-panel-geochart.html
2) Click on Geo chart tab in footer panel
3) All the layers which have charts are displayed but charts are not displayed for each layer.

**Comment by Alex-NRCan** [comment]
This issue makes sense and seems to be the essential modifications necessary for the GeoChart Plugin to work differently than originally planned (having the layers on the left panel) - indeed.

I would probably suggest to fetch the data only when a layer is selected in the UI (not fetch all layers when a chart for a layer isn't really being shown). For performance reasons.

(side note, this issue is different than the one I've started looking at on Friday Dec 1st [https://github.com/Canadian-Geospatial-Platform/geochart/issues/54](https://github.com/Canadian-Geospatial-Platform/geochart/issues/54) which is really _GeoChart component_ related and not _GeoChart plugin_ related like this present issue here)
