### ISSUE TITLE
Support Geopackages

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/geoview#183]
Have the ability to consume GeoPackages. There is already an npm module who does that: https://www.npmjs.com/package/@ngageoint/leaflet-geopackage. Take a look to see if it is suitable or if we have to create our own.

**Comment by LarryWang888** [comment]
The leaflet-geopackage package (https://www.npmjs.com/package/@ngageoint/leaflet-geopackage) cannot be installed into our GeoView Package because:
- it's outdated and has not been upgraded in the last 2 years.
- it has many unsolved reported issues, like #172 Incompatible with Node.js >= 14.0.0

Alternative solutions:
(1) Waiting for them to upgrade the leaflet-geopackage package
(2) instead of adding the NPM  leaflet-geopackage package,  directly use and import leaflet-geopackage.js in our geoview package, however, the leaflet-geopackage.js has a size of 7MB.
(3) create our own light weight codes to read  geopackage data

Need further investigation.

**Comment by yass0016** [comment]
@LarryWang888 is this the only geopackage module available for leaflet?

**Comment by LarryWang888** [comment]
@yass0016 yes, so far it's the only one available for leaflet. There is another Geopackage Js library: https://www.npmjs.com/package/geopackage, which is created 5 years ago

**Comment by jolevesq** [comment]
@LarryWang888 It means it will require some work to get this done. We will move this to icebox until we get client requirements

**Comment by DamonU2** [comment]
Working on using sql.js to convert geopackages to WKB, which is supported by openlayers. This will also add WKB support to geoview.

**Comment by jvanulde** [comment]
Demo here: https://canadian-geospatial-platform.github.io/geoview/public/geopackage.html
