### ISSUE TITLE
[FEATURE] Add layer panel to appBar

### ISSUE THREAD

**Issue by namangera** [Canadian-Geospatial-Platform/geoview#1889]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Who request this Feature

Naman Gera, CHN team, NRCan

### User Story

it would be great for the appBar and footerBar to have the same components, especially the layer-panel. My team has shown a preference for the layer-panel in the appBar.

**Comment by jolevesq** [comment]
There is component that will not move to app bar because of their complexity or available room. Data table, chart, slider and layers may be part of this.

To use in app bar, the component should be simple to use due to restriction in size. For app bar the legend can be use and we have an issue to add basic function like show/hide layer to it. #1838 

The footer bar goal is to make navigation easier (more room and tab with labels). From our experience, users had difficulties to use the actual RAMP with only appp bar and needed a bunch of buttons outside the viewer to help user navigate. The goal is to avoid this.
