### ISSUE TITLE
Can the keyboard shortcut for disabling Keyboard Navigation use only Esc key instead?

### ISSUE THREAD

**Issue by Malvoz** [Canadian-Geospatial-Platform/GeoView#190]
When disabling Keyboard Navigation with the assigned <kbd>Shift</kbd> + <kbd>Esc</kbd> keys the Task Manager is opened on my machine. Can it perhaps be disabled using only <kbd>Esc</kbd> instead?

The <kbd>Esc</kbd> key alone is commonly used to escape the current context, such as closing a dialog (default behavior for `<dialog>` in Chrome, for example).

**Comment by jolevesq** [comment]
Thank for your input.

We can't only use the esc key because it is use to exit context of specific thing inside the viewer like to close open panel or exit active tool. It is why we would need a combination of keys.

I had alt - esc but modified it because on my windows it shift windows.

I will need a new key combination... if you have any idea I would be glad to hear.

**Comment by jolevesq** [comment]
I put CTRL + Q as key combo to exit the focus trap. I have tested on my Mac and Windows computer and nothing was triggered by this combo. If a better combo is found along the way I can update it.
