### ISSUE TITLE
[BUG] Chart config - Full screen mode disabled the "Steps" menu

### ISSUE THREAD

**Issue by MLAuger** [Canadian-Geospatial-Platform/geoview#2248]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using the "Package geochart" config, if the map is put in full screen mode, the "Steps" drop-down menu of the chart is disabled. You can't open it.

### Expected Behavior

The "Steps"drop-down menu should offer you the folowing options as usual: 
![image](https://github.com/Canadian-Geospatial-Platform/geoview/assets/91547284/b2142d66-691b-452d-90ba-c5d2e7747386)

### Steps To Reproduce

1. Select the Package geochart config
2. Click on a "Airborne Radioactivity" station point
3. go in the chart menu
4. Put map in full screen
5. Try to open the "Steps" drop-down menu

### Anything else?

When you disabled the Full screen mode, the drop-down menu appears, floating over the map: 
![image](https://github.com/Canadian-Geospatial-Platform/geoview/assets/91547284/0ad3b11c-e45f-4555-8ef3-01649cf96a2d)

**Comment by cphelefu** [comment]
@jolevesq this is a complex error that meets the eye.
The error is happening because MuiSelect renders a Popover the bottom the page (when showing Select options). This cause it to not be visible. We had this problem with the Popover before. But we simply set the container property of the Popover (check Notifications component).

In this case the Select is rendered in a different project (geochart).

geoview-geochart > src >chart.tsx, lines 1558.
