### ISSUE TITLE
Use one render function as a parent level

### ISSUE THREAD

**Issue by yass0016** [Canadian-Geospatial-Platform/GeoView#27]
Instead of rendering maps separately each as its own parent, create a render function that will render the maps as child components. This will help with sharing state and context.

**Comment by jolevesq** [comment]
@yass0016 comments

It's always good to have one root component to be able to share the state, context between all the children, in this case these two samples. I tried a different approach but because the map container components take a few seconds to load both <span>'s in the index.html that are displayed above each sample will render before the maps render. This is the reason I kept both maps to render on their own div although this is not the best practice when building a react app to have React components render on separate divs, for our case maybe this is the best approach. I can try to look for better solutions to have the maps render on the same root component if you want.

**Comment by jolevesq** [comment]
Yes, can you take a look at best practice to have multiple react app on a same page. I want different app because they need to have their own i18n instance attach to them.

Keep in mind the way we would like to handle state between maps. With React hooks all children get the state from parent. We need to think how we can propagate the state so we can have outside listener  for those hooks.

**Comment by yass0016** [comment]
Running multiple react apps in the same page will impact performance. I will find a solution to have both maps render on their own divs while sharing state that can be exported and be used in outside listener without impacting performance.

Because this issue is related to issue #10 I will work on it when I start working on that issue.

**Comment by yass0016** [comment]
I found the best way to do it without losing any performance and keeping all created divs / spans and all elements in the index.html to render in the correct order. And with sharing a global store since any created app or element will dynamically be added as a child of the root component

The method I used is by storing all elements in the body tag and then dynamically rendering them in a newly created root div.

This way will allow us to render as many apps / divs in index.html

**Comment by jolevesq** [comment]
Perfect! Can you implement this and a some structure to the HTML page to show case that the new created map will go at the desire place on the page?

**Comment by yass0016** [comment]
I have re-implemented it in a different way 

Parsing nested divs then re-rendering them is complex and will slow down performance since we would have to write a recursive function that will generate a structure possibly a JSON structure then re-rendering it using React elements. This will also require us to create a parsing function that would parse every html tag which is cumbersome and hence decided to go in another route.

The current implementation will still work perfectly, currently we are still rendering a root component which we can pass a global state to it. Each map will render on it's own component and we can pass the state down to it's tree.

I have pushed the code to https://github.com/yass0016/GeoView/tree/%2327-rendering

Also you can view the demo at https://yass0016.github.io/GeoView/index.html

It does seem to render quicker for me, not sure if this improved any performance or it's just my device.

**Comment by jolevesq** [comment]
It loads fast, that's good. Not able to compare between the 2 to see the differences. There is one problem, we miss the translation files in your deploy (https://jolevesq.github.io/GeoView/index.html if you look at the tooltip).

Are you happy with the solution you are proposing? If so, we can go with this and revisit later. What so you think?

**Comment by yass0016** [comment]
Yes, you are right, I am not able to see the tooltips being translated in my deploy. I am able to see them when running it locally. What do you think could cause this? Is it just a deploy issue? When I deploy I do "npm run build" then "npm run deploy"

For now I am satisfied with this solution, I would still have to test the global state next in #10 to see if I will be able to access it from both maps.
