### ISSUE TITLE
Find a way to make API calls after maps are ready

### ISSUE THREAD

**Issue by yass0016** [Canadian-Geospatial-Platform/GeoView#56]
Currently we can make API calls from outside our app (specifically from index.html at the moment)
The problem is that some API calls requires a leaflet map instance to be ready and we are creating this map instance using react leaflet when we render MapContainer
The issue is that rendering is taking few seconds and running API calls will be called earlier and cause an error or return undefined because they are being called on an undefined object since the Map is not ready yet.
We need to find a way to make those API calls after the map is ready

**Comment by jolevesq** [comment]
Instead of being able to call the api on page load can we something like the onDocument.ready? We listent for the first API event who is mapReady. Once this done and know map is ready then we can all other API functions.

This is how it is done for the eari api who needs to load dependencies before we are able to access them.
```
// get ESRI TimeExtent dependency (for image server) and start slider creation
let myBundlePromise = (<any>window).RAMP.GAPI.esriLoadApiClasses([['esri/TimeExtent', 'timeExtent']]);
   myBundlePromise.then(myBundle => {
   new SliderManager(mapApi, this.panel, extendConfig, myBundle);
});
```

We can even define what event or event group (layer, map, ...) we want to register on. Empty means everything.

**Comment by yass0016** [comment]
this might work if we have only 1 map to be loaded, we currently have 2 maps and for issue #49 we will probably have 3. There might be a way in React to check that all rendering is finished then we can emit an event that all maps are ready and then we can call the APIs
