### ISSUE TITLE
Switch LegendItem to use legend event payload

### ISSUE THREAD

**Issue by dayc-mapdev** [Canadian-Geospatial-Platform/geoview#615]
See TODO comments in legend-item.tsx. Ideally we want an event option to get legend for a single layer.

In the legend.html example / mapId=UC3 (with the esri-dynamic group layer) throws an error when event options are used

**Comment by ychoquet** [comment]
The LegendsLayerSet class will get the leend for each layer on the map. It only call the getLegend once. If you ask the legend an other time, since all the legend of the map are already loaded, no query is done and the previous legendsLayerSet is returned. Only if you dynamically load an other layer will trigger a getLayer and only for the added layer. So, we can use the legendsLayerSet wit a layerPath index to get a single layer without querying if the legend is already loaded.
