### ISSUE TITLE
Enforce https for image

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/geoview#735]
When use the hydro service: https://maps.geogratis.gc.ca/wms/hydro_network_en the images and get capabilities are using http and it creates error.

```
xhr.js:210 Mixed Content: The page at 'https://canadian-geospatial-platform.github.io/geoview/public/package-layers-panel.html' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://maps.geogratis.gc.ca/wms/hydro_network_en?version=1.3.0&service=WMS&request=GetLegendGraphic&sld_version=1.1.0&layer=nhn:nhn&format=image/png&STYLE=default'. This request has been blocked; the content must be served over HTTPS.
```

**Comment by elatsis** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/GeoView-Web-Team-6332f4560a41153d1fefbcbc/issues/Canadian-Geospatial-Platform/geoview/735?planning-poker) with Zenhub @ychoquet

**Comment by ychoquet** [comment]
The problem is not caused by the use of a http call. It is the hydro layer that define a style that points to a bad http query that returns an error saying htat the layer parameter mentioned in the http query is bad. I wrote a correction to avoid the error trace in the console and returned an undefined legend entry (null).
