### ISSUE TITLE
Linestring clusters not splitting last two features

### ISSUE THREAD

**Issue by DamonU2** [Canadian-Geospatial-Platform/geoview#764]
When a layer config is loaded from HTML (works fine when using config file) that clusters line strings, two features remain clustered no matter the zoom. Can be seen at: https://canadian-geospatial-platform.github.io/geoview/public/cluster.html, works as expected in top map when loaded from config file, but on the second map the features remain clustered.

**Comment by ychoquet** [comment]
Based on the debugging and the traces I followed, this is normal when the feature is a Multi geometry (MultiPoint, MultiLineString and MultiPolygon) because a single feature contains many representation. This will also happen with simple geometry when they share the same position (many points at the same coordinate).
