### ISSUE TITLE
[BUG] Feature position discrepancy between ESRI Dynamic and ESRI Feature 

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/geoview#931]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There is difference in feature position when we compare ESRI Dynamic and ESRI Feature representation. This may come from symbology anchor point not handle properly.

### Expected Behavior

When we add the same layer Dynamic and Feature, features should overlap

### Steps To Reproduce

1. Go to https://canadian-geospatial-platform.github.io/geoview/public/package-layers-panel.html
2. Add esri Dynamic: https://maps-cartes.services.geo.ca/server_serveur/rest/services/NRCan/historical_flood_event_en/MapServer
3. Add esri Feature: https://maps-cartes.services.geo.ca/server_serveur/rest/services/NRCan/historical_flood_event_en/MapServer/0
4. Toggle view layer

### Anything else?

![image](https://user-images.githubusercontent.com/3472990/222144914-10a157aa-fbcc-460e-9e05-2b8fc352a77a.png)

**Comment by DamonU2** [comment]
The discrepancy is caused by the way the icons are handled by the different types. The dynamic layer is using the center of the small ball end of the icon as the anchor point, while the feature layer uses the center point  of the icon. It does not seem like enough data is provided with the legend to fix this in the feature layer without hard coding. The only positional data provided with the legend items are angle (always 0) and x and y offsets, and they are all 0,1 except for one which is 0,1.1.
"symbol": {
      "type": "esriPMS",
      "url": "5cfde73608ec8972846ed702a499be52",
      "imageData": "iVBORw0KGgoAAAANSUhEUgAAAAwAAAAUCAYAAAC58NwRAAAAAXNSR0IB2cksfwAAAAlwSFlzAAAOxAAADsQBlSsOGwAAAZ1JREFUKJGV0UFLG0EUwPF/stqhcWnosoZuCFQQiqCeNm0991bQL5C9b25d9hOonyDEiyT37AdQz168BMxKIT1oQaiipgS6xdqRjpBsD0mr0S2xDwaGx/x4782b4D9j4s/FcHxb9vprAIr4wtC0etSohInAcHxXPjNrmC8gayKur5CdE1eUvFAF1eIIMBzflk8yNWYXIKMPshkdTAvaTdtwfDdqVOp/gaS/wnT+9vHdmF1AHuy6wC1QvdgSevbxQxuaFsqfl4MWHgOi+NeOOPsMuUJyW/cBwebFlOMX5cFui7fvYXJyDACiRiU0HL8sP+7VeP1uPBiiunC8PO3mKotL4wGAalTXRMlb5suhzczceACggmpRlLwWetYma4LQ83eX9wAAqFS8Lr593cK0YP6NJY8/1UTJc1VQLSYCeiwjng7uGR0Wl6DdtHE+rCQCkU7Z5AqjSesl4kfXTq7Qp8P11egiOyco4jB5hvRNWRzun1N4Bc9z8L0Ll92QYGM7ucJw+9HpkcvpEUJLdaZS6W3FP34JBtsHygBqeAB+A13uj5E0Bn/BAAAAAElFTkSuQmCC",
      "contentType": "image/png",
      "width": 9,
      "height": 15,
      "angle": 0,
      "xoffset": 0,
      "yoffset": 1
     },
