### ISSUE TITLE
[BUG] PyGEOAPi process not loading as layer

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/geoview#958]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We are not able to load PyGeoApi as ...

**Comment by grefton** [comment]
**Current Behavior**
We are not able to load PyGeoApi Process result as a geoview layer that can be added to the layer panel.
The pygeoapi processes requires defining a POST request with parameters defined as POST parameters.
The geoview layers configuration only allows specific layer types, such as wms or esri map service, not OGC API - Processes.

**Expected Behavior**
1. Define a layer based on the processes json definition. e.g. http://\<url\>/processes/downstream-analysis?f=json
2. Set the POST parameters e.g.
{
    "inputs": {
        "inSRID": 4326,
        "lat": 45.1823,
        "long": -72.0556,
        "outSRID": 4326
    }
}
4. Execute the process with the POST parameters.  http://\<url\>/processes/downstream-analysis/execution
5. Display the results on the map and display a new layer in the layers panel

The geoview api should allow adding a layer based on a POST request with configured parameters to the pygeoapi processes task and view the results on the map and in the layers panel.

**Steps To Reproduce**
Try adding processes end point to the layers list.

**Anything else?**
Please contact the CHN team at NRCAN for sample internal URL end points and additional sample POST parameters and expected results.

**Comment by jolevesq** [comment]
JSON OGC API - Processes endpoint http://132.156.9.48:30102/processes/drainage?f=jsonHere's an example that returns a single geojson Polygonhttp://132.156.9.48:30102//processes/drainage/executionPOST parameters{
  "inputs": {
    "inSRID": 3978,
    "lat": 45.1812079916714,
    "long": -72.05892966849758,
    "outSRID": 4326
  }
} Here is a sample post request that returns a one multipolygon{
  "inputs": {
    "inSRID": 3978,
    "lat": 45.24446686647312,
    "long": -72.19582735219994,
    "outSRID": 4326
  }
}
